 <?php

/**Author : Oladele John

** © 2022 Oladele John

** Edtech classroom

** File name : create-course/create-course-processor/create-course-controller.php

** About : this controller controlls the course create model

*/

/**PSUEDO ALGORITHM
 * *
 * initiate the create course controller class
 * then define the controller function and ....
 * 
 */

class createCourseController{

    public function controller(){

        include('create-course-model.php');

        $create_course = new createCourse();

        $create_course->fetchCourseData();

        if(!empty($_POST['courseCode']) && !empty($_POST['courseTitle']) && 
        !empty($_POST['level']) && !empty($_POST['aboutCourse'])){

            //require the env library
            require('../../vendorEnv/autoload.php');

            $user_db_conn_env = Dotenv\Dotenv::createImmutable(__DIR__, '../../env/db-conn-var.env');
            $user_db_conn_env->load();

            // user db connection
            include('../../resources/database/courses-db-connection.php');

            $create_course->sanitized_course_code = $create_course->sanitize($conn8,$create_course->course_code);

            $create_course->sanitized_course_title = $create_course->sanitize($conn8,$create_course->course_title);

            $create_course->sanitized_level = $create_course->sanitize($conn8,$create_course->level);

            $create_course->sanitized_about_course = $create_course->sanitize($conn8,$create_course->about_course);

            $create_course->sanitized_course_outline = $create_course->sanitize($conn8,$create_course->course_outline);

            $create_course->fetchLecturerData();

            $create_course->cachedLecturerDataQuery();

            $create_course->definingLecturerData();

            $create_course->autoGeneratedData();

            $create_course->neccessasryCourseTable();

            $create_course->courseClassTable();

            $create_course->createCourseOutlineFile();

            $create_course->insertIntoCourseTable();

            $create_course->redirect();

            mysqli_close($conn8);

        }else{

            echo "Empty course form";

        }

    }

}

session_start();

$create_course_controller = new createCourseController();

if(isset($_SESSION['lecturer_session'])){

    $create_course_controller->controller();

}else{

    echo 'Session is not set';

}

 ?>