<?php

/**Author : Oladele John

** © 2022 Oladele John

** Edtech classroom

** File name : signup/lecturer-sign-up-processor/lecturer-sign-up-controller.php

** About : this controller controlls the lecturer sign up model

*/

/**PSUEDO ALGORITHM
 * *
 * initiate the lecturer sign up controller class
 * then define the controller function and ....
 * 
 */

class lecturerSignupController{

    public $title;

    public $fullname;

    public $username;

    public $about;

    public $avatar_filename;

    public $sign_up_status;

    //then define the controlleer function and ....
    public function controller(){

       //include the lecturer sign up model
       include('lecturer-sign-up-model.php');

       $lecturer_sign_up = new lecturerSignUp();

       $lecturer_sign_up->fetchLecturerData();
 
        //checking if the all fetched lecturer data were submitted
        if(!empty($lecturer_sign_up->title) && !empty($lecturer_sign_up->email) && 
        !empty($lecturer_sign_up->name) && !empty($lecturer_sign_up->gender) 
        && !empty($lecturer_sign_up->about) && !empty($lecturer_sign_up->username) 
        && !empty($lecturer_sign_up->password) && !empty($_FILES['avatar']['type'])){

            //require the env library
            require('../../vendorEnv/autoload.php');

            $user_db_conn_env = Dotenv\Dotenv::createImmutable(__DIR__, '../../env/db-conn-var.env');
            $user_db_conn_env->load();

            // user db connection
            include('../../resources/database/users-db-connection.php');

            $lecturer_sign_up->sanitized_title = 
            $lecturer_sign_up->sanitize($conn1,$lecturer_sign_up->title);

            $lecturer_sign_up->sanitized_email = 
            $lecturer_sign_up->sanitize($conn1,$lecturer_sign_up->email);

            $lecturer_sign_up->sanitized_name = 
            $lecturer_sign_up->sanitize($conn1,$lecturer_sign_up->name);

            $lecturer_sign_up->sanitized_gender = 
            $lecturer_sign_up->sanitize($conn1,$lecturer_sign_up->gender);

            $lecturer_sign_up->sanitized_about = 
            $lecturer_sign_up->sanitize($conn1,$lecturer_sign_up->about);

            $lecturer_sign_up->sanitized_username = 
            $lecturer_sign_up->sanitize($conn1,$lecturer_sign_up->username);

            $lecturer_sign_up->sanitized_password = 
            $lecturer_sign_up->sanitize($conn1,$lecturer_sign_up->password);

            $lecturer_sign_up->autoGeneratedData();

            $lecturer_sign_up->lecturerResetPassword();

            $lecturer_sign_up->lecturerNotification();

            $lecturer_sign_up->processingLecturerAvatar();

            $lecturer_sign_up->insertLecturerIntoDb();
            
            mysqli_close($conn1);

            //Setting up profile preveiew varaibles
            $this->title = $lecturer_sign_up->sanitized_title;

            $this->fullname = $lecturer_sign_up->sanitized_name;

            $this->username = $lecturer_sign_up->sanitized_username;

            $this->about = $lecturer_sign_up->sanitized_about;

            $this->avatar_filename = $lecturer_sign_up->avatar_file_name;

            $this->sign_up_status = $lecturer_sign_up->sign_up_status;

        }else{

            echo "Not set";

        }

    } 

}

?>