<?php

/**Author : Oladele John

** © 2022 Oladele John

** Web application

** File name : classes/class-assignment/submit-assignnment-model.php

** About : this module allows the student to submit their assignment

*/ 

session_start();

class submitAssignmentController{

    public function controller(){

        include('submit-assignment-model.php');

        $submit_assignment = new submitAssignment();

        session_regenerate_id(true);

        if(isset($_SESSION['student_session'])){

            $submit_assignment->fetchStudentSession();

            $submit_assignment->fetchStudentData();

            $submit_assignment->cacheStudentData();

            $submit_assignment->defineStudentData();

            $submit_assignment->fetchAssignmentData();

            //$current_date = date("Y-m-d");

            if($submit_assignment->assignment_status == "Active"){

                //require the env library
               require('../../vendorEnv/autoload.php');

               $user_db_conn_env = Dotenv\Dotenv::createImmutable(__DIR__, '../../env/db-conn-var.env');
               $user_db_conn_env->load();

               include('../../resources/database/courses-classes-assignments-db-connection.php');

               $submit_assignment->sanitized_assignment_answer = 
               $submit_assignment->sanitize($conn16,$submit_assignment->assignment_answer);

                $submit_assignment->defineAutoGeneratedData();

               $submit_assignment->insertIntoAssignment();

               $submit_assignment->alertLecturer();

               $submit_assignment->redirectStudent();

               mysqli_close($conn16);  
               
               echo "Its active";

            }else{

                header("location:class-assignment-expired-error.php");  

            }

        }else{

            header('location:logout-success.php');

        }

    }

}

$submit_assignment_controller = new submitAssignmentController();

$submit_assignment_controller->controller();

?>