<?php

/**Author : Oladele John

** © 2022 Oladele John

** Web application

** File name : classes/class-test/create-class-test.php

** About : this module creates the lecturer class test

*/ 

/**PSUEDO ALGORITHM
 * *
 * define the class create class test
 * fetch the create class test input form data
 * sanitize the input form data
 * create the auto generated data
 * create the class test auto generated tables
 * insert the sanitized class test inputes and the auto generated data
 * 
 * *
*/

session_start();

//define the class create class test
class createClassTest{

    public $class_encrypted_id;

    public $test_title;

    public $no_of_questions;

    public $minutes_limit;

    public $seconds_limits;


    public $sanitized_test_title;

    public $sanitized_no_of_question;

    public $sanitized_minutes_limit;

    public $sanitized_seconds_limit;


    public $test_encrypted_id;

    public $date_created;

    public $time_created;

    public $status;

    //fetch the create class test input form data
    public function fetchClassTestInputs(){

        $this->class_encrypted_id = $_POST['classEncryptedId'];

        $this->test_title = $_POST['testTitle'];

        $this->no_of_questions = $_POST['noOfQuestion'];

        $this->minutes_limit = $_POST['minutesLimit'];

        $this->seconds_limits = $_POST['secondsLimit'];

    }

    //sanitize the input form data
    public function sanitize($connection,$data){

        $data = htmlspecialchars($data);
        $data = stripslashes($data);
        $data = strip_tags($data);
        //$data = $connection->real_escape_string($data);

        return $data; 

    }

    //create the auto generated data
    public function createAutoGeneratedData(){

        $this->test_encrypted_id = md5(rand());

        $this->date_created = date("Y/m/d");

        $this->time_created = date("h:i:sa");

        $this->status = "active";

    }

    //create the class test auto generated tables
    public function createStudentTestAnswers(){

        // class test db connection
        include('../../resources/database/class-test-result-db-connection.php');

        $create_students_answers_table = "CREATE TABLE students_of_class_test_".$this->test_encrypted_id."
        (
         id int NOT NULL AUTO_INCREMENT,
         student_fullname text,
         student_username text,
         student_matric_number text,
         student_avatar text,
         student_encrypted_id text,
         final_result text,
         status text,
         PRIMARY KEY(id)
        )";

        if($conn20->query($create_students_answers_table)){

            echo "Students answers table created";

        }else{

            echo "Could not create students answers table";

        }

        mysqli_close($conn20);

    }

    public function createLecturerTestAnswers(){

        // class test db connection
        include('../../resources/database/class-test-result-db-connection.php');

        $create_lecturer_answers_table = "CREATE TABLE lecturer_of_class_test_".$this->test_encrypted_id."
        (
         id int NOT NULL AUTO_INCREMENT,
         lecturer_fullname text,
         lecturer_username text,
         lecturer_avatar text,
         lecturer_encrypted_id text,
         final_result text,
         status text,
         PRIMARY KEY(id)
        )";

        if($conn20->query($create_lecturer_answers_table)){

            echo "Lecturer answers table created";

        }else{

            echo "Could not create lecturer answers table";

        }

        mysqli_close($conn20);

    }

    public function createTestQuestions(){

        // class test db connection
        include('../../resources/database/class-test-questions-db-connections.php');

        $create_test_questions_table = "CREATE TABLE test_questions_of_class_test_".$this->test_encrypted_id."
        (
         id int NOT NULL AUTO_INCREMENT,
         question_title text,
         question_encrypted_id text,
         optionA text,
         optionB text,
         optionC text,
         optionD text,
         correct_option text,
         status text,
         PRIMARY KEY(id)
        )";

        if($conn21->query($create_test_questions_table)){

            echo "Lecturer answers table created";

        }else{

            echo "Could not create lecturer answers table";

        }

        mysqli_close($conn21);

    }

    //insert the sanitized class test input and the auto generated data
    public function insertIntoClassTest(){

        // class test db connection
        include('../../resources/database/class-test-db-connection.php');

        $insert_into_class_test = "INSERT INTO test_of_class_".$this->class_encrypted_id."
        (
            test_title,total_no_questions,minutes_limit,seconds_limit,test_encrypted_id,date_created,time_created,status
        )
        VALUES(
            '$this->sanitized_test_title','$this->sanitized_no_of_question','$this->sanitized_minutes_limit','$this->sanitized_seconds_limit'
            ,'$this->test_encrypted_id','$this->date_created','$this->time_created','$this->status'
        )
        ";

        if($conn19->query($insert_into_class_test)){

            header("location:lecturer-test-initializer.php?classEncryptedId=$this->class_encrypted_id&&testEncryptedId=$this->test_encrypted_id");

        }else{

            echo "Could not insert into the class test db";

        }

    }

}

$create_class_test = new createClassTest();

if(isset($_SESSION['lecturer_session'])){

    if(isset($_POST['testTitle']) && $_POST['testTitle'] !== "" && isset($_POST['noOfQuestion']) && $_POST['noOfQuestion'] !== "" 
    && isset($_POST['minutesLimit']) && $_POST['minutesLimit'] !== "" && isset($_POST['secondsLimit']) && $_POST['secondsLimit'] !== ""){

        $create_class_test->fetchClassTestInputs();

        // class test db connection
        include('../../resources/database/class-test-db-connection.php');

        $create_class_test->sanitized_test_title = $create_class_test->sanitize($conn19,$create_class_test->test_title);

        $create_class_test->sanitized_no_of_question = $create_class_test->sanitize($conn19,$create_class_test->no_of_questions);

        $create_class_test->sanitized_minutes_limit = $create_class_test->sanitize($conn19,$create_class_test->minutes_limit);

        $create_class_test->sanitized_seconds_limit = $create_class_test->sanitize($conn19,$create_class_test->seconds_limits);

        mysqli_close($conn19);

        $create_class_test->createAutoGeneratedData();

        $create_class_test->createStudentTestAnswers();

        $create_class_test->createLecturerTestAnswers();

        $create_class_test->createTestQuestions();

        $create_class_test->insertIntoClassTest();

    }

}

?>