<?php

/**Author : Oladele John

** © 2022 Oladele John

** Web application

** File name : courses/create-classroom/create-clasroom-controller.php

** About : this module controlls the create classroom model

*/ 

/**PSUEDO ALGORITHM
 * *
 * initiate the create classroom controller class
 * then define the controller function and ....
 * 
 */

session_start();

//initiate the create classroom controller class
class createClassroomController{

    //then define the controller function and ....
    public function controller(){

       include('create-classroom-model.php');

       $create_classroom = new createClassroom();

       $create_classroom->fetchLecturerSession();

       $create_classroom->fetchClassData();

        if(!empty($create_classroom->class_note) && !empty($create_classroom->class_topic) && 
        !empty($create_classroom->about_class) && !empty($create_classroom->class_assignment) && 
        !empty($create_classroom->due_date) && !empty($create_classroom->course_encrypted_id)){

          echo "Class created";

          //require the env library
          require('../../vendorEnv/autoload.php');

          $user_db_conn_env = Dotenv\Dotenv::createImmutable(__DIR__, '../../env/db-conn-var.env');
          $user_db_conn_env->load();

          // course db connection
          include('../../resources/database/courses-classes-db-connection.php');

          echo $create_classroom->sanitized_class_note = $create_classroom->sanitize($conn10,$create_classroom->class_note);

          $create_classroom->sanitized_class_topic = $create_classroom->sanitize($conn10,$create_classroom->class_topic);

          $create_classroom->sanitized_about_class = $create_classroom->sanitize($conn10,$create_classroom->about_class);

          $create_classroom->sanitized_class_assignment = $create_classroom->sanitize($conn10,$create_classroom->class_assignment);

          $create_classroom->sanitized_due_date = $create_classroom->sanitize($conn10,$create_classroom->due_date);

          $create_classroom->sanitized_course_encrypted_id = $create_classroom->sanitize($conn10,$create_classroom->course_encrypted_id);

          $create_classroom->sanitized_course_code = $create_classroom->sanitize($conn10,$create_classroom->course_code);

          $create_classroom->autoGeneratedData();

          $create_classroom->classAttendaceTable();

          $create_classroom->classAssignmentTable();

          $create_classroom->classTestTable();
          
          $create_classroom->processClassNote();

          $create_classroom->insertIntoClassromDatabase();

          $create_classroom->redirectLecturer();

        }else{

          echo "Empty class form";

        }

    }

}

$create_classroom_controller = new createClassroomController();

$create_classroom_controller->controller();


?>